export const FEATCH_ARTICLES_REQUEST = "FEATCH_ARTICLES_REQUEST";
export const FEATCH_ARTICLES_SUCCESS = "FEATCH_ARTICLES_SUCCESS";
export const FEATCH_ARTICLES_FAILURE = "FEATCH_ARTICLES_FAILURE";
export const FEATCH_ARTICLES_CLEARE = "FEATCH_ARTICLES_CLEARE";

export const FEATCH_ARTICLE_REQUEST = "FEATCH_ARTICLE_REQUEST";
export const FEATCH_ARTICLE_SUCCESS = "FEATCH_ARTICLE_SUCCESS";
export const FEATCH_ARTICLE_FAILURE = "FEATCH_ARTICLE_FAILURE";
export const FEATCH_ARTICLE_CLEARE = "FEATCH_ARTICLE_CLEARE";

export const EDIT_ARTICLE_REQUEST = "EDIT_ARTICLE_REQUEST";
export const EDIT_ARTICLE_SUCCESS = "EDIT_ARTICLE_SUCCESS";
export const EDIT_ARTICLE_FAILURE = "EDIT_ARTICLE_FAILURE";
export const EDIT_ARTICLE_CLEARE = "EDIT_ARTICLE_CLEARE";

export const REMOVE_ARTICLE_REQUEST = "REMOVE_ARTICLE_REQUEST";
export const REMOVE_ARTICLE_SUCCESS = "REMOVE_ARTICLE_SUCCESS";
export const REMOVE_ARTICLE_FAILURE = "REMOVE_ARTICLE_FAILURE";
export const REMOVE_ARTICLE_CLEARE = "REMOVE_ARTICLE_CLEARE";
